### ISSUE TITLE
Sidebar 移入，出现滚动条

### ISSUE THREAD

**Issue by menggeNiu** [NewDadaFE/react-impression#251]
![image](https://user-images.githubusercontent.com/22184471/46202336-296f7780-c349-11e8-8bcc-1fa3ac2ad4af.png)

**Comment by lusssn** [comment]
问题原因是perfect-scrollbar插件导致的。
是否要将此插件移除呢？
@bipedd @menggeNiu @wjeek

**Comment by lusssn** [comment]
![image](https://user-images.githubusercontent.com/7519187/48244769-40ae8400-e422-11e8-9897-99fb8eca1f10.png)

**Comment by bipedd** [comment]
如果移除perfect-scrollbar，在出现滚动条的时候，样式会变丑吗？

**Comment by lusssn** [comment]
> @lusssn 如果移除perfect-scrollbar，在出现滚动条的时候，样式会变丑吗？

就是跟着不同系统上的原生样式走了
