### ISSUE TITLE
Tooltip内容是为可跳转链接的时候，跳转到新页面，Tooltip不消失

### ISSUE THREAD

**Issue by menggeNiu** [NewDadaFE/react-impression#418]
![image](https://user-images.githubusercontent.com/22184471/50141709-25694b00-02e3-11e9-881c-90e9de41b4e7.png)
![image](https://user-images.githubusercontent.com/22184471/50141715-2c905900-02e3-11e9-9618-d42fe6fe351b.png)
tootip内容可点击，点击后跳转到新页面，但是tooltip不消失

**Comment by lusssn** [comment]
原本就是有这个问题，所以说改成css实现的，结果css实现的导致它层级不能够在最上面。就换了popper，结果，popper定位又会导致定位错乱，代码回滚。
因此，目前这个问题无解

**Comment by u19900101** [comment]
手动让他消失：$('.tooltip-show').tooltip('destroy');
