### ISSUE TITLE
 Select & Input  value显示问题

### ISSUE THREAD

**Issue by terrytang66** [NewDadaFE/react-impression#419]
通过接口获取数据详情，默认设置 < Select value={detail.id}  /> 若初始化的数据detail中没有id字段，后期通过接口直接获取，会出现如图情况，需要自己手动去置空才可正确显示 < Select value={detail.id || ''}  />, Input输入框同理。
![image](https://user-images.githubusercontent.com/5364201/50196973-4633ae00-0380-11e9-94f2-9d7498d76dc1.png)

**Comment by menggeNiu** [comment]
上述情况，初始化detail没有id，所以select value传进去的是undefined，因此变成非受控组件。可给detail里面的id一个默认值null或者-1之类不对后台造成逻辑判断的值。
