### ISSUE TITLE
Checkbox组件有哪些功能需要完善？

### ISSUE THREAD

**Issue by bipedd** [NewDadaFE/react-impression#49]

**Comment by wjeek** [comment]
- [ ] 增加半选模式

- [ ] CheckboxGroup将direction属性转变为是否垂直排列的boolean类型属性

**Comment by lusssn** [comment]
- [ ] 组件接受结构较复杂的children，例如：![Uploading image.png…]()

**Comment by bipedd** [comment]
> CheckboxGroup将direction属性转变为是否垂直排列的boolean类型属性

@wjeek 建议废弃direction属性，新增一个
