### ISSUE TITLE
SelectOption组件增加过滤掉非dom属性

### ISSUE THREAD

**Issue by gwt9502** [NewDadaFE/react-impression#520]
SelectOption组件接受外部传入的props，如果接受一些dom不支持的熟悉会引起react渲染时的警告   
![image](https://user-images.githubusercontent.com/25758249/88615030-9ed23d80-d0c3-11ea-8253-39ae34100ed9.png)   
[pull request链接](https://github.com/NewDadaFE/react-impression/pull/522)

**Comment by lusssn** [comment]
pr：#523
